// Generated by CoffeeScript 1.8.0
(function() {
  var HEIGHT, WIDTH, addAttribute, createIbo, createProgram, createVBO, fragmentShaderSource, loadShader, m, mMatrix, mvpMatrix, pMatrix, startLoop, tmpMatrix, vMatrix, vertexShaderSource;

  WIDTH = 500;

  HEIGHT = 300;

  vertexShaderSource = "attribute vec3 position;\nattribute vec4 color;\nuniform   mat4 mvpMatrix;\nvarying   vec4 vColor;\n\nvoid main(void){\n    vColor = color;\n    gl_Position = mvpMatrix * vec4(position, 1.0);\n}";

  fragmentShaderSource = "precision mediump float;\nvarying vec4 vColor;\nvoid main(void){\n    gl_FragColor = vColor;\n}";

  window.assets = {};

  assets.position = new Float32Array([0.0, 1.0, 0.0, 1.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, -1.0, 0.0]);

  assets.color = new Float32Array([1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]);

  assets.indexBuffer = new Int16Array([0, 1, 2, 1, 2, 3]);

  loadShader = function(gl, type, source) {
    var shader;
    shader = gl.createShader(type);
    gl.shaderSource(shader, source);
    gl.compileShader(shader);
    if (!gl.getShaderParameter(shader, gl.COMPILE_STATUS)) {
      throw new Error(gl.getShaderInfoLog(shader));
    }
    return shader;
  };

  createProgram = function(gl, vs, fs) {
    var program;
    program = gl.createProgram();
    gl.attachShader(program, vs);
    gl.attachShader(program, fs);
    gl.linkProgram(program);
    if (!gl.getProgramParameter(program, gl.LINK_STATUS)) {
      throw new Error(gl.getProgramInfoLog(program));
    }
    gl.useProgram(program);
    return program;
  };

  createVBO = function(gl, data) {
    var vbo;
    vbo = gl.createBuffer();
    gl.bindBuffer(gl.ARRAY_BUFFER, vbo);
    gl.bufferData(gl.ARRAY_BUFFER, data, gl.STATIC_DRAW);
    gl.bindBuffer(gl.ARRAY_BUFFER, null);
    return vbo;
  };

  addAttribute = function(gl, program, vbo, name, argsCount, type) {
    var attr;
    if (type == null) {
      type = gl.FLOAT;
    }
    gl.bindBuffer(gl.ARRAY_BUFFER, vbo);
    attr = gl.getAttribLocation(program, name);
    gl.enableVertexAttribArray(attr);
    return gl.vertexAttribPointer(attr, argsCount, type, false, 0, 0);
  };

  createIbo = function(gl, data) {
    var ibo;
    ibo = gl.createBuffer();
    gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER, ibo);
    gl.bufferData(gl.ELEMENT_ARRAY_BUFFER, data, gl.STATIC_DRAW);
    gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER, null);
    return ibo;
  };

  m = new matIV();

  mMatrix = m.identity(m.create());

  vMatrix = m.identity(m.create());

  pMatrix = m.identity(m.create());

  tmpMatrix = m.identity(m.create());

  mvpMatrix = m.identity(m.create());

  startLoop = function(gl) {
    var colorVBO, count, fragmentShader, ibo, locationUniform, positionVBO, program, update, vertexShader;
    count = 0;
    vertexShader = loadShader(gl, gl.VERTEX_SHADER, vertexShaderSource);
    fragmentShader = loadShader(gl, gl.FRAGMENT_SHADER, fragmentShaderSource);
    program = createProgram(gl, vertexShader, fragmentShader);
    ibo = createIbo(gl, assets.indexBuffer);
    gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER, ibo);
    positionVBO = createVBO(gl, assets.position);
    colorVBO = createVBO(gl, assets.color);
    addAttribute(gl, program, positionVBO, 'position', 3);
    addAttribute(gl, program, colorVBO, 'color', 4);
    locationUniform = gl.getUniformLocation(program, 'mvpMatrix');
    m.lookAt([0.0, 0.0, 5.0], [0, 0, 0], [0, 1, 0], vMatrix);
    m.perspective(45, WIDTH / HEIGHT, 0.1, 100, pMatrix);
    m.multiply(pMatrix, vMatrix, tmpMatrix);
    return (update = function() {
      var rad;
      gl.clearColor(0.0, 0.0, 0.0, 1.0);
      gl.clearDepth(1.0);
      gl.clear(gl.COLOR_BUFFER_BIT);
      count++;
      rad = (count % 360) * Math.PI / 180;
      m.identity(mMatrix);
      m.rotate(mMatrix, rad, [0, 1, 0], mMatrix);
      m.multiply(tmpMatrix, mMatrix, mvpMatrix);
      gl.uniformMatrix4fv(locationUniform, false, mvpMatrix);
      gl.drawElements(gl.TRIANGLES, assets.indexBuffer.length, gl.UNSIGNED_SHORT, 0);
      gl.flush();
      return requestAnimationFrame(update);
    })();
  };

  window.addEventListener('load', function() {
    var canvas, gl;
    canvas = document.createElement('canvas');
    document.body.appendChild(canvas);
    canvas.width = WIDTH;
    canvas.height = HEIGHT;
    gl = canvas.getContext('webgl');
    return startLoop(gl);
  });

}).call(this);
